# SPDX-FileCopyrightText: 2025 Andrey Kotlyar <guitar0.app@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

[[annotations]]
path = [
    "pdm.lock",
    "**/__pycache__/",
    "**/*.pyc",
    "**/.DS_Store",
    "infrastructure/ansible/.vault_pass",
    "infrastructure/ansible/inventory/group_vars/production.yml",
    "infrastructure/ansible/inventory/group_vars/staging.yml",
]
precedence = "closest"
SPDX-FileCopyrightText = "Andrey Kotlyar <guitar0.app@gmail.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
