# SPDX-FileCopyrightText: 2025 Andrey Kotlyar
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

[[annotations]]
path = ["pdm.lock"]
precedence = "closest"
SPDX-FileCopyrightText = "Andrey Kotlyar <guitar0.app@gmail.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
