# SPDX-FileCopyrightText: 2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

all:
  children:
    production:
      hosts:
        prod-server:
          ansible_host: "{{ lookup('env', 'PRODUCTION_HOST') | default('api.guitar0.net', true) }}"
          ansible_user: deploy
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_FILE') | default('~/.ssh/id_rsa', true) }}"
