# SPDX-FileCopyrightText: 2025-2026 Andrey Kotlyar <guitar0.app@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PDM with cache
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: |
            pdm.lock
            pyproject.toml

      - name: Install dependencies
        run: pdm install --frozen-lockfile

      - name: Ruff â€” lint checks
        run: pdm run ruff check .

  typecheck:
    name: Mypy type checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    env:
      SECRET_KEY: "dummy-secret-key"
      DATABASE_URL: "sqlite:///test.db"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PDM with cache
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: |
            pdm.lock
            pyproject.toml

      - name: Install dependencies
        run: pdm install --frozen-lockfile

      - name: Run MyPy
        run: pdm run mypy --strict .

  tests:
    name: Pytest + Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    env:
      SECRET_KEY: "dummy-secret-key"
      DATABASE_URL: "sqlite:///test.db"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PDM with cache
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: |
            pdm.lock
            pyproject.toml

      - name: Install dependencies
        run: pdm install --frozen-lockfile

      - name: Run unit tests
        run: pdm run pytest --maxfail=1 --cov --cov-branch --cov-report=xml --cov-fail-under=90 -m "not integration"

      - name: Run integration tests
        run: pdm run pytest --maxfail=1 --cov --cov-branch --cov-report=xml --cov-append -m "integration"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: guitar0-net/server
          files: coverage.xml

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [lint, typecheck, tests]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infrastructure/docker/Dockerfile
          platforms: linux/amd64
          push: false
          tags: kotlyar562/guitar0net:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
